export const CREATE_TODO = "CREATE_TODO";
export const CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS";
export const CREATE_TODO_FAILURE = "CREATE_TODO_FAILURE";
export const UPDATE_TODO = "UPDATE_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const DELETE_ALL_COMPLETED_TODOS = "DELETE_ALL_COMPLETED_TODOS";
export const GET_TODOS_LIST = "GET_TODOS_LIST";
export const GET_TODO_BY_ID = "GET_TODO_BY_ID";
